"""remove_categories

Revision ID: 2e34774cd62b
Revises: b0ba2ebe25e3
Create Date: 2026-02-26 17:16:03.155414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2e34774cd62b'
down_revision: Union[str, None] = 'b0ba2ebe25e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_category_limits_budget_plan_id', table_name='budget_category_limits')
    op.drop_table('budget_category_limits')
    op.add_column('budget_plans', sa.Column('flexible_planned', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.drop_column('budget_plans', 'fun_spending_planned')
    op.drop_column('budget_plans', 'essentials_planned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_plans', sa.Column('essentials_planned', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('budget_plans', sa.Column('fun_spending_planned', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_column('budget_plans', 'flexible_planned')
    op.create_table('budget_category_limits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('budget_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('limit_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_plan_id'], ['budget_plans.id'], name='budget_category_limits_budget_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='budget_category_limits_pkey')
    )
    op.create_index('ix_budget_category_limits_budget_plan_id', 'budget_category_limits', ['budget_plan_id'], unique=False)
    # ### end Alembic commands ###
