"""Budget lockbox and 3 buckets

Revision ID: 49d1d51623e5
Revises: 2e34774cd62b
Create Date: 2026-02-26 17:33:44.977245
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49d1d51623e5'
down_revision: Union[str, None] = '2e34774cd62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_plans', sa.Column('top_line_income', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('budget_plans', sa.Column('hard_commitments_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('budget_plans', sa.Column('net_available', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('budget_plans', sa.Column('reserve_pct', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False))
    op.add_column('budget_plans', sa.Column('goals_pct', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False))
    op.add_column('budget_plans', sa.Column('free_pct', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False))
    op.add_column('budget_plans', sa.Column('free_money_planned', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_plans', 'free_money_planned')
    op.drop_column('budget_plans', 'free_pct')
    op.drop_column('budget_plans', 'goals_pct')
    op.drop_column('budget_plans', 'reserve_pct')
    op.drop_column('budget_plans', 'net_available')
    op.drop_column('budget_plans', 'hard_commitments_total')
    op.drop_column('budget_plans', 'top_line_income')
    # ### end Alembic commands ###
