"""add expense_kind to expenses

Revision ID: 9fd658fa1814
Revises: da1aa894b988
Create Date: 2026-02-25 22:05:31.491569
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9fd658fa1814'
down_revision: Union[str, None] = 'da1aa894b988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_kind', sa.String(length=20), server_default='variable', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'expense_kind')
    # ### end Alembic commands ###
