"""budget rewrite

Revision ID: b0ba2ebe25e3
Revises: 9fd658fa1814
Create Date: 2026-02-26 16:49:07.097783
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0ba2ebe25e3'
down_revision: Union[str, None] = '9fd658fa1814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_fixed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('goals', sa.Column('last_auto_funded_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'last_auto_funded_date')
    op.drop_column('expenses', 'is_fixed')
    # ### end Alembic commands ###
